"""FX fix reversal test - see ../FX_FIX_TEST_PLAN.md (pre-registered).

Run from the repo root:  python3 "Vanessa Algo Bots/research/scripts/fx_fix_test.py"
"""
import csv
import datetime as dt
import math
import statistics as st
from collections import defaultdict
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "Vanessa Algo Bots/research/data"
UK = ZoneInfo("Europe/London")
PIP = 0.0001
COSTS = {"base": 1.0, "stress": 2.0}      # pips per round trip
HOURS = (8, 16, 21)
TEST_START = dt.date(2019, 1, 1)
CAL_END = dt.date(2018, 12, 31)


def load(name):
    days = defaultdict(dict)
    for r in csv.DictReader(open(DATA / f"{name.lower()}_h1.csv")):
        t = dt.datetime.fromtimestamp(int(r["timestamp_ms"]) / 1000, dt.timezone.utc).astimezone(UK)
        if t.weekday() < 5 and t.minute == 0 and t.hour in HOURS:
            days[t.date()][t.hour] = float(r["open"])
    return {d: p for d, p in days.items() if len(p) == 3}


def legs(prices, cost_pips):
    """{leg: [(date, net_bp, gross_bp)]}"""
    out = defaultdict(list)
    for d in sorted(prices):
        p8, p16, p21 = (prices[d][h] for h in HOURS)
        pre = -(p16 / p8 - 1) * 1e4                     # short the pair = long USD
        post = (p21 / p16 - 1) * 1e4                    # long the pair = short USD
        c_pre = cost_pips * PIP / p8 * 1e4
        c_post = cost_pips * PIP / p16 * 1e4
        out["Pre-fix (08-16, long USD)"].append((d, pre - c_pre, pre))
        out["Post-fix (16-21, short USD)"].append((d, post - c_post, post))
        out["Both legs"].append((d, pre + post - c_pre - c_post, pre + post))
    return out


def stats(xs):
    n = len(xs)
    m = st.mean(xs)
    sd = st.stdev(xs)
    return n, m, m / (sd / math.sqrt(n)), m / sd * math.sqrt(252), 100 * sum(x > 0 for x in xs) / n


out = []
P = out.append
P("# FX fix reversal test - results\n")
P("Generated by `research/scripts/fx_fix_test.py`. Plan: `research/FX_FIX_TEST_PLAN.md`.")
P("bp = basis point = 0.01%. Sharpe is annualised from daily returns (252 days).\n")

verdict = {}
for sym in ("EURUSD", "GBPUSD"):
    prices = load(sym)
    ds = sorted(prices)
    P(f"## {sym} ({ds[0]} .. {ds[-1]}, {len(ds)} days)\n")
    for per_name, lo, hi in (("Calibration 2012-2018", dt.date(2012, 1, 1), CAL_END),
                             ("TEST 2019-2026", TEST_START, dt.date(2100, 1, 1))):
        P(f"### {per_name}\n")
        P("| Leg | Days | Gross mean | Net mean (1 pip) | Net t | Net Sharpe | Win % | Net mean (2 pips) |")
        P("|---|---|---|---|---|---|---|---|")
        base, stress = legs(prices, COSTS["base"]), legs(prices, COSTS["stress"])
        for leg in base:
            b = [x for d, x, _ in base[leg] if lo <= d <= hi]
            g = [x for d, _, x in base[leg] if lo <= d <= hi]
            s = [x for d, x, _ in stress[leg] if lo <= d <= hi]
            n, m, t, sh, win = stats(b)
            P(f"| {leg} | {n} | {st.mean(g):+.2f} bp | {m:+.2f} bp | {t:+.2f} | {sh:+.2f} | {win:.0f}% | {st.mean(s):+.2f} bp |")
        P("")
        if per_name.startswith("TEST"):
            P("| Year | Pre-fix net | t | Post-fix net | t | Both net |\n|---|---|---|---|---|---|")
            yearly = defaultdict(lambda: defaultdict(list))
            for leg, rows in base.items():
                for d, x, _ in rows:
                    if d >= TEST_START:
                        yearly[d.year][leg].append(x)
            pos_years = defaultdict(int)
            for y in sorted(yearly):
                cells = []
                for leg in ("Pre-fix (08-16, long USD)", "Post-fix (16-21, short USD)"):
                    n, m, t, _, _ = stats(yearly[y][leg])
                    pos_years[leg] += m > 0
                    cells.append(f"{m:+.2f} bp | {t:+.2f}")
                P(f"| {y} | {' | '.join(cells)} | {st.mean(yearly[y]['Both legs']):+.2f} bp |")
            P("")
            for leg in ("Pre-fix (08-16, long USD)", "Post-fix (16-21, short USD)"):
                n, m, t, _, _ = stats([x for d, x, _ in base[leg] if d >= TEST_START])
                ok = m > 0 and t > 2 and pos_years[leg] >= 5
                verdict[(sym, leg)] = ok
                P(f"- **{leg}: {'PASS' if ok else 'FAIL'}** (net {m:+.2f} bp, t {t:+.2f}, positive in {pos_years[leg]} of {len(yearly)} years)")
            P("")

text = "\n".join(out)
(ROOT / "Vanessa Algo Bots/research/results/FX_FIX_TEST_RAW.md").write_text(text + "\n")
print(text)
